name: C++ Tests

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches: ['*']

jobs:
  run-tests:
    name: Build and Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ libopencv-dev

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build tests
        run: cmake --build build --config Release

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure